"use client";
import { Download, HardDriveDownload, RefreshCcw, ShieldCheck, Upload } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import type { ManagedBookState } from "@/app/lib/semester";

type Backup={id:number;createdAt:string;sourceUpdatedAt:string};
export function Backups({state,onRestored,onImport}:{state:ManagedBookState;onRestored:()=>void;onImport:(state:ManagedBookState)=>void}){
 const [items,setItems]=useState<Backup[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/backups",{cache:"no-store"});if(r.ok){const data=await r.json() as {backups:Backup[]};setItems(data.backups);}}
 useEffect(()=>{void load();},[]);
 function download(){const blob=new Blob([JSON.stringify({format:"caderno-coc-backup",exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`caderno-coc-${state.activeSemesterId}-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);}
 async function snapshot(){setBusy(true);setMessage("");const r=await fetch("/api/backups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"snapshot"})});setMessage(r.ok?"Backup manual criado com sucesso.":"Não foi possível criar o backup.");await load();setBusy(false);}
 async function restore(id:number){if(!confirm("Restaurar esta cópia? Um backup do estado atual será criado antes da restauração."))return;setBusy(true);const r=await fetch("/api/backups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"restore",id})});setMessage(r.ok?"Backup restaurado com sucesso.":"Não foi possível restaurar o backup.");if(r.ok)onRestored();setBusy(false);}
 async function upload(file:File){try{const value=JSON.parse(await file.text()) as {state?:ManagedBookState};const imported=value.state??value as unknown as ManagedBookState;if(!imported.students||!Array.isArray(imported.students))throw new Error();if(confirm("Importar este arquivo e substituir o estado atual? O servidor criará uma cópia automática antes de salvar."))onImport(imported);}catch{setMessage("Arquivo de backup inválido.");}}
 return <div className="view-stack"><section className="page-title-row"><div><span className="eyebrow">PROTEÇÃO DE DADOS</span><h1>Backups e restauração</h1><p>O sistema guarda automaticamente uma cópia por dia e mantém as 30 mais recentes.</p></div><div className="student-actions"><button className="action-button secondary" onClick={download}><Download size={16}/> Baixar backup</button><button className="action-button" disabled={busy} onClick={()=>void snapshot()}><ShieldCheck size={16}/> Criar cópia agora</button></div></section>{message&&<div className="backup-message">{message}</div>}<section className="panel backup-import"><div><Upload/><span><strong>Restaurar arquivo do computador</strong><small>Selecione um arquivo JSON baixado por este caderno.</small></span></div><input type="file" accept=".json,application/json" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></section><section className="panel simple-list"><div className="simple-row backup-row simple-header"><span>Cópia</span><span>Data do backup</span><span>Dados salvos em</span><span/></div>{items.map(x=><div className="simple-row backup-row" key={x.id}><span><HardDriveDownload/><strong>Backup #{x.id}</strong></span><span>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.createdAt))}</span><span>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(x.sourceUpdatedAt))}</span><span><button className="mini-action restore" disabled={busy} onClick={()=>void restore(x.id)}><RefreshCcw size={12}/> Restaurar</button></span></div>)}{!items.length&&<div className="empty-state"><HardDriveDownload/><strong>Nenhuma cópia automática ainda</strong><span>A primeira será criada antes da próxima alteração ou pelo botão acima.</span></div>}</section></div>;
}
